service:
  host: 0.0.0.0
  port: 8888

logger:
   logInFile: true
   outputDir: "./logs/"

database:
  database: postgresql
  passwordFilePath: ./secret/postgres.pass
  userName: postgres
  url: localhost:5432/postgres
  sslMode: disable

  driverName: postgres

jwt:
  iss: dkiliyevich@gmail.com
  signingFilePath: ./secret/jwt.pass
  sessionTokenLen: 32
  sessionSigningLen: 128
  accessTokenExp: 16m
  refreshTokenExp: 8760h


mail:
  serverName: smtp.yandex.ru:465  
  username: digitaltrace@yandex.ru
  password: goklphsnczpwmuow